export const GET_MODAL_STATUS = 'GET_MODAL_STATUS';
export const SET_MODAL_STATUS = 'SET_MODAL_STATUS';

export const ADD_NEW_ACCOUNT = 'ADD_NEW_ACCOUNT';
export const FETCH_ALL_ACCOUNTS = 'FETCH_ALL_ACCOUNTS';
export const FETCH_RECENT_ACCOUNTS = 'FETCH_RECENT_ACCOUNTS';
export const FETCH_IND_ACCOUNT = 'FETCH_IND_ACCOUNT';

export const ADD_NEW_CERTIFICATE = 'ADD_NEW_CERTIFICATE';
export const FETCH_ALL_CERTIFICATES = 'FETCH_ALL_CERTIFICATES';
export const FETCH_RECENT_CERTIFICATES = 'FETCH_RECENT_CERTIFICATES';
export const FETCH_IND_CERTIFICATE = 'FETCH_IND_CERTIFICATE';

export const ADD_NEW_FORM = 'ADD_NEW_FORM';
export const FETCH_ALL_FORMS = 'FETCH_ALL_FORMS';
export const FETCH_RECENT_FORMS = 'FETCH_RECENT_FORMS';
export const FETCH_IND_FORM = 'FETCH_IND_FORM';

export const ADD_NEW_RESPONSE = 'ADD_NEW_RESPONSE';
export const FETCH_ALL_RESPONSES = 'FETCH_ALL_RESPONSES';
export const FETCH_RECENT_RESPONSES = 'FETCH_RECENT_RESPONSES';
export const FETCH_IND_RESPONSE = 'FETCH_IND_RESPONSE';

export const ADD_NEW_TRAINING = 'ADD_NEW_TRAINING';
export const FETCH_ALL_TRAININGS = 'FETCH_ALL_TRAININGS';
export const FETCH_RECENT_TRAININGS = 'FETCH_RECENT_TRAININGS';
export const FETCH_IND_TRAINING = 'FETCH_IND_TRAINING';

export const ADD_NEW_USER = 'ADD_NEW_USER';
export const FETCH_ALL_USERS = 'FETCH_ALL_USERS';
export const FETCH_RECENT_USERS = 'FETCH_RECENT_USERS';
export const FETCH_IND_USER = 'FETCH_IND_USER';

export const CHECK_USER_LOGIN = 'CHECK_USER_LOGIN';
export const FETCH_LOGIN_USER = 'FETCH_LOGIN_USER';